version: "3.8"

services:
  app:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: forum
    volumes:
      - forum-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: forum_db

volumes:
  forum-vol:
